const assert = require('node:assert/strict');
const { Simulation, Gardener } = require('./dist/game-core.js');
let sim = new Simulation(() => .2);
assert.equal(sim.plant(-1, 0, 'saxaul'), false);
assert.equal(sim.plant(0, 0, 'saxaul'), false, 'ocean is outside the planting boundary');
assert.equal(sim.plant(16, 12, 'saxaul'), true);
assert.equal(sim.plant(16, 12, 'saxaul'), false);
assert.equal(sim.live, 0, 'new seedlings cannot advance ecology before survival');
for (let i = 1; i < 80; i++) sim.plant(16 + i % 20, 12 + Math.floor(i / 20), 'saxaul');
sim.step(4);
assert.equal(sim.live, 80); assert.equal(sim.seedlings, 0); assert.equal(sim.phase, 3);
assert.deepEqual(sim.drainEvents().map(e => e.type), ['phase', 'phase', 'phase', 'ending']);
assert.equal(sim.drainEvents().length, 0);
assert.ok(sim.wind > 0 && sim.wind < .98);
assert.equal(sim.plant(30, 22, 'flower'), true, 'planting continues after the ending');
const initialWind = new Simulation(() => .2);
assert.ok(initialWind.survival('saxaul') > initialWind.survival('willow'));
assert.ok(initialWind.survival('willow') > initialWind.survival('flower'));
function grove(species) { const s = new Simulation(() => .2); for (let i = 0; i < 20; i++) s.plant(20 + i % 10, 15 + Math.floor(i / 10), species); s.step(4); return s; }
assert.ok(grove('willow').wind < grove('saxaul').wind, 'sand willow shelters the grove more');
assert.ok(grove('flower').soil > grove('saxaul').soil, 'flowering shrubs improve soil more');
assert.ok(grove('willow').survival('flower', 24, 17) > grove('willow').survival('flower', 40, 20), 'neighboring living trees improve survival');
const dying = new Simulation(() => .999);
dying.plant(26, 18, 'saxaul'); dying.step(4);
assert.equal(dying.live, 0); assert.equal(dying.dead, 1); assert.equal(dying.phase, 0);
assert.equal(dying.plant(26, 18, 'saxaul'), true, 'dead saplings can be replanted');
sim.random = () => 0; sim.step(30);
assert.ok(sim.dead > 0, 'natural loss continues in a restored ecosystem');
assert.equal(sim.live, sim.cells.filter(t => t?.state === 'live').length);
assert.equal(sim.seedlings, sim.cells.filter(t => t?.state === 'seed').length);
const island = new Simulation(() => .2), gardener = new Gardener(island);
assert.equal(gardener.canStand(gardener.x, gardener.y), true);
const planted = gardener.plant('saxaul'); assert.ok(planted);
assert.ok(Math.hypot(planted.x + .5 - gardener.x, planted.y + .5 - gardener.y) <= 1.8, 'planting stays within the character reach');
const originalX = gardener.x; gardener.walk(1, 0, 1); assert.ok(gardener.x > originalX, 'the character moves');
gardener.walk(1, 0, 20); assert.ok(gardener.canStand(gardener.x, gardener.y), 'the coast blocks the character from walking into the ocean');
assert.equal(gardener.canStand(0, 0), false);
console.log('PASS: island boundary, character movement and planting reach, survival, species tradeoffs, ecology and ending.');
